#!/bin/sh
# Make sure local dependencies are satisfied.

cd "$(dirname $0)"/..

rm -f .bundle/config

(bundle check --path .bundle > /dev/null 2>&1 && [ -d bin ]) ||
  bundle install --binstubs bin --path .bundle
